### ISSUE TITLE
Mention somewhere that the tool only works on Windows

### ISSUE THREAD

**Issue by amine4567** [CookiePLMonster/GT2-Combined-Disc#4]
Maybe it's not that important because most people use Windows but I think it would be nice to mention somewhere in the README that the tool currently only works on Windows because there are no Linux or macOS versions of GTVolTool (at least as far as I know).

**Comment by CookiePLMonster** [comment]
GTVolTool is written in C# so you're probably right. I can mention that in the readme.

**Comment by CookiePLMonster** [comment]
Addressed in 83ddc586319136e938a2d4293a65c48a6100c45a
